#ifndef _EMULATOR_CONSTANTS_H
#define _EMULATOR_CONSTANTS_H

#define MAX_SYMBOL_NAME 32

#define MEMORY_SIZE (1 << 16)

#define SECTION_UND 0
#define SECTION_TEXT 1
#define SECTION_DATA 2
#define SECTION_RODATA 3
#define SECTION_BSS 4

#define SECTION_CNT 5

#define SYMTYPE_SYM 0
#define SYMTYPE_SECTION 1

#define LINKAGE_LOCAL 0
#define LINKAGE_GLOBAL 1

#define RELOCATION_PC_RELATIVE 0
#define RELOCATION_ABSOLUTE 1

#define REGISTER_PC 7
#define REGISTER_SP 6

#define INSTRUCTION_SET_SIZE 16

#define MNEMONIC_ADD 0
#define MNEMONIC_SUB 1
#define MNEMONIC_MUL 2
#define MNEMONIC_DIV 3
#define MNEMONIC_CMP 4
#define MNEMONIC_AND 5
#define MNEMONIC_OR 6
#define MNEMONIC_NOT 7
#define MNEMONIC_TEST 8
#define MNEMONIC_PUSH 9
#define MNEMONIC_POP 10
#define MNEMONIC_CALL 11
#define MNEMONIC_IRET 12
#define MNEMONIC_MOV 13
#define MNEMONIC_SHL 14
#define MNEMONIC_SHR 15

#define INSTR_COND_EQUAL 0
#define INSTR_COND_NOT_EQUAL 1
#define INSTR_COND_GREATER_THAN 2
#define INSTR_COND_NONE 3

#define OPERAND_IMM 0
#define OPERAND_PSW 1
#define OPERAND_REGDIR 2
#define OPERAND_MEMDIR 3
#define OPERAND_REGINDIR 4

#define START_SYMBOL "START"

#define IVT_MEM_START 0
#define IVT_MEM_END 15

#define PER_MEM_START 0xFF80
#define PER_MEM_END 0xFFFF

#define KBD_INPUT_REG 0xFFFC
#define TERM_OUTPUT_REG 0xFFFE

#define NEG_NUM_RANGE_START 0x8000

#define PSW_BIT_ZERO 0
#define PSW_BIT_OVERFLOW 1
#define PSW_BIT_CARRY 2
#define PSW_BIT_NEGATIVE 3

#define PSW_BIT_TIMER_IRQ_MASK 13
#define PSW_BIT_GLOBAL_IRQ_MASK 15

#define INTERRUPT_ROUTINE_START 0
#define INTERRUPT_ROUTINE_TIMER 1
#define INTERRUPT_ROUTINE_ILLEGAL_INSTR 2
#define INTERRUPT_ROUTINE_KBD 3

#define INTERRUPT_ROUTINE_KILL 7

#endif